server:
  port: ${SERVER_PORT:8282}
spring:
  application: 
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: service_credito
#          uri: lb://MSCREDITO
#          predicates:
#            - Path=/mscredito/**
#          filters:
#            - RewritePath=/mscredito/(?<remaining>.*), /$\{remaining}
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: "*"